language: node_js
node_js:
  - "stable"

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

env:
  global:
    secure: i1QYB0Gr3CLHWRDekTeFbmIB5+2/d5lNIFQ5/V34+4w3hSGOK0HYz8ChidO8Qlx027X0fve6yM059t3vBpBHrRfVf51kWh2Ijs0jJTOUxgenOT+/jTz/2TJJHAlkzce1JXr2UiKk1jeNFbIn5HF+/OBElfqLcB+JR/XJKNx7vknhD4z1JtFri72bbPw1Z/9baiiTVSZz0/RT/WQpA4gISGuodRy7ZDCxYwiLa5nWldj0RGL761b6iW4rdlLanCkjO07QywhTAn0bpzKxaVP/j43qmi3TJfDgTCl1zp2Vft2gHu9bvco6gJDyWnTg0dkRdoqt1T4hfqh+z+O935X3wAZvTYwqTlwqnHVBDZfUt37qUmxvbcTfl50NRdmcJLgsgtOUssU6HbvreDfnnaeLJJ/mJA5AFOeaUfpyVrgQXM+dmGK9vH6B55VjDAldTowx84J6cSUl8tIj8w0d+hLZmSh84FtaUvSNOpfl0iwDPuiBCvd0H8qqwpRi6VmCA/WNZPk1pHiQScy0/jV0Kg6nk14bKVVwLK3bJ2iQ1asbv8UMjcXhWoOE9C0y4FxDcgtXN54m55nVxaztJPDo++1RhyYb0bt3EISAwmAfyTjdobQ4Bmo6yWH77VvlurtOcDzAIknkRkP3t5XbIQq5M6uRkJHbl8r64Hv1FL0bvO5/6YE=