language: node_js
node_js:
  - "stable"

before_install:
- openssl aes-256-cbc -K $encrypted_XXXXXXXX_iv -iv $encrypted_XXXXXXXX_key -in .travis/id_ras.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa 
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'liuvigongzuoshi'
- git config --global user.email liuvigongzuoshi@foxmail.com

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master
