language: node_js
node_js:
  - "stable"

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

env:
  global:
    secure: emXXrj553bitvmV92PSuU5INFpSLqXXYy5ggS2UyLTtvY0UfzcooQ5s/RD6gJY2uJ26v6eaa9fWzCJjTXWwGLU06i4k13CXwYMmxYol8wlDqvK3JLjZ1EA74LU4lBhAn9WR6gUlz2294hCISPM+nGHgiymEuGTbmLJt/AS8h3jIuon87IRP99F0zTyWIh9wF1sb2jPWybVvY/ilqP8Pqec8/ig8imhfRGSQuekcWfU8/vfJi6HFnI/TWlaQ8+8sxDKGqh/i+OnzcmPw+MOg+8SKU1ypvrnOMV4qZ3g83DjllSPVj1SslPrMIqss1opOm2LRCL/epFUqjueC8wO4duy6YhD0tKgAPr5exLKP9SK6ELZC83XDDptL5DhH2XsqEb/EhoMylQ08ipZ2YklfmDo/aSpvPuxQrkg/DH9erF2DQdAc5w1FZeIOLE/2NOtb4t3p54u6oBui0XjOkZxR6fQneZxy/+36zAg5fDKOfhl3fxxgghu0i8Rb3XAGNXelZyKeU6joz8Jwlt3JAkFnnyXsGTuPzFl1hcEwNCVRV4SR/pE1PUvwAp3fZxMMUXPjtUmQUjNb4M3GXaG25c5O35ibB7mvnWd4E4wv/am5SqY9vmLLFUeK/y2Ybfi0lAJfnCclYnG31aK/gYl6hqK4tS40pd0tdj/dM0TnMe3dhJJo=