language: node_js
node_js:
  - "stable"

install:
  - npm install

script:
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  local_dir: build
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master